version: "2"

services:
  frontend:
    image: bertinabogo/frontend-app:latest
    container_name: express-frontend
    ports:
      - "8080:8080"
    networks:
      - proxy

  backend:
    image: bertinabogo/backend-app:latest
    container_name: express-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=MyRealBackendPassword123!
      - DB_NAME=tasksdb
      - DB_PORT=3306
      - PORT=3000
    networks:
      - proxy
    depends_on:
      - database

  database:
    image: bertinabogo/mariadb-custom:latest
    container_name: mariadb-container
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: MyRealBackendPassword123!
      MARIADB_DATABASE: tasksdb
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - proxy

networks:
  proxy:
    external: true
